language: python
python:
  - "3.7"
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" .
  - python setup.py install
# command to run tests
script: pytest
after_success:
    - codecov